apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: "postgres-pod"
    app: demo-voting-app
  type: ClusterIP
  ports:
  - name: postgres-service-port
    protocol: TCP
    port: 5432
    targetPort: 5432