apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis-pod
    app: demo-voting-app
  type: ClusterIP
  ports:
  # - name: redis-port
  - port: 6379
    targetPort: 6379

