apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  selector:
    name: voting-app
    app: demo-voting-app
  type: NodePort
  ports:
  - name: voting-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30080